language: ruby
install: bundle install -j 4 --retry 3
script:
  - RAILS_ENV=test bundle exec rspec spec
services:
  - redis-server

matrix:
  include:
    - rvm: "1.9.3"
      gemfile: gemfiles/Gemfile-old-ruby
    - rvm: "2.0.0"
      gemfile: gemfiles/Gemfile-old-ruby
    - rvm: "2.1.0"
      gemfile: gemfiles/Gemfile-old-ruby
    - rvm: "2.1.5"
      gemfile: gemfiles/Gemfile-old-ruby
    - rvm: "2.2.1"
      gemfile: gemfiles/Gemfile-old-ruby
    - rvm: "2.2.2"
      gemfile: gemfiles/Gemfile-ruby2.2.2
    - rvm: "2.3.0"
    - rvm: "2.3.3"
    - rvm: "2.4.1"
