version: '3.7'

services:
  app:
    image: ruby:2.6
    volumes:
      - .:/app
    working_dir: /app
    command: bash
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      BUNDLE_PATH: /app/.gems

  redis:
    image: redis:5.0.6
